#!/usr/bin/expect -f

set timeout 30
set server "149.33.0.114"
set user "root"
set password "D7V7vcfK2i"

spawn ssh ${user}@${server}
expect {
    "password:" {
        send "${password}\r"
    }
    "yes/no" {
        send "yes\r"
        expect "password:"
        send "${password}\r"
    }
}

expect "# "
send "cat /root/sense-of-dance/backend/.env | grep MONGODB_URI\r"

expect "# "
send "exit\r"
expect eof

