FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx-local.conf /etc/nginx/conf.d/default.conf
COPY frontend /usr/share/nginx/html
RUN chmod -R a+rX /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
