#!/usr/bin/expect -f
set timeout 30

spawn scp /Users/poirtyc/Desktop/sense-of-dance/frontend/public/*.html root@149.33.0.114:/root/sense-of-dance/frontend/public/
expect "password:"
send "D7V7vcfK2i\r"
expect eof

spawn ssh root@149.33.0.114
expect "password:"
send "D7V7vcfK2i\r"

expect "# "
send "pm2 restart sense-of-dance-frontend\r"

expect "# "
send "echo 'HTML files fixed - using original JS files!'\r"

expect "# "
send "exit\r"

expect eof
